# Generated by Django 2.2.1 on 2020-04-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='tags',
        ),
        migrations.AddField(
            model_name='clothing',
            name='tags',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Tags', verbose_name='标签'),
            preserve_default=False,
        ),
    ]
