# Generated by Django 2.2.1 on 2020-04-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200414_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='name',
            field=models.CharField(max_length=32, verbose_name='服装名称'),
        ),
    ]
